spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://postgres:5432/db_test"
    username: guest
    password: guest_pwd