spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://db_changelog:5432/SchoolOrganisation"
    username: takima
    password: takimapass